### ISSUE TITLE
Does this support multiline text?

### ISSUE THREAD

**Issue by reworks-org** [nyyManni/msdfgl#13]
Hi, @nyyManni ,
nice job with the library.

I was wondering if this library supports multi-line text rendering using the line height of the font?

Thanks.

**Comment by lczyk** [comment]
@nyyManni would you accept PR for this? just implemented it in my version for ``msdfgl_printf`` in a pretty simple way..

**Comment by nyyManni** [comment]
PRs are always welcome, so go ahead! :)
