### ISSUE TITLE
resetting glViewport any time after glyph(s) generation

### ISSUE THREAD

**Issue by xornet-sl** [nyyManni/msdfgl#5]
This general code seems to be ok:
```C++
// ....
// general GLFW, window and GLAD initialization
// ....
glfwGetFramebufferSize(window, &fb_width, &fb_height);
glViewport(0, 0, fb_width, fb_height);
// ....

msdfgl_context_t ctx = msdfgl_create_context("330 core");
msdfgl_atlas_t atlas = msdfgl_create_atlas(ctx, 1024, 2);
msdfgl_font_t font = msdfgl_load_font(ctx, "Arial.ttf", 4, 2, atlas);
msdfgl_generate_ascii(font);
// glfwGetFramebufferSize(window, &fb_width, &fb_height);
// glViewport(0, 0, fb_width, fb_height);
msdfgl_set_missing_glyph_callback(ctx, msdfgl_generate_glyph, NULL);
_msdfgl_ortho(0.0, fb_width, fb_height, 0.0, -1.0, 1.0, proj);
while (!glfwWindowShouldClose(window)) {
    processInput();
    glClearColor(0.05f, 0.05f, 0.05f, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);
    msdfgl_printf(0, 64, font, 64, 0xffffffff, (GLfloat *)proj,
                          static_cast<msdfgl_printf_flags>(MSDFGL_UTF8 | MSDFGL_KERNING), "Hello world!");
    glfwSwapBuffers(window);
    glfwPollEvents();
}
```

But I encounter in one very annoying thing here. Any time when msdfgl library is generating glyphs (via `_msdfgl_generate_glyphs_internal` which is called either by `msdfgl_generate_ascii` or through callback) I SHOULD restore glViewport (commented lines right after `msdfgl_generate_ascii(font);`. This is becouse `_msdfgl_generate_glyphs_internal` sets the Viewport inside theirs own framebuffer but doesn't restore it when done.
so if I have `glViewport(0, 0, fw_width, fb_height)` before any glyps generation and then I am trying to print any text I see the mess I attached. But of course I have this nice callback that fixes everything, but only after resizing:
```C++
inline void Engine::onFramebufferResize(GLFWwindow *window, int width, int height) {
    auto &e = Engine::Instance();
    glfwGetFramebufferSize(window, &e.fb_width, &e.fb_height);
    glViewport(0, 0, e.fb_width, e.fb_height);
    _msdfgl_ortho(0.0, e.fb_width, e.fb_height, 0.0, -1.0, 1.0, proj);
}
```
I see this behaviour in demo file too. I running it on Debian 10.
Maybe there could be another one callback that will be called after glyphs generation and restore the viewport? Or I totally wrong somewhere and just should use it in some another way?
![Снимок экрана от 2020-04-05 03-35-32](https://user-images.githubusercontent.com/7584765/78464177-a6be3a00-76ee-11ea-8ab0-aacf58064005.png)

Things go harder if I don't want to pregenerate any glyps at all (just like in demo file) and print every time a new text with new symbols. Any time right after `msdfgl_printf` my Viewport will be broken! it is totally not expected behaviour!

**Comment by nyyManni** [comment]
Would it do the trick if I just query the current viewport with 
```c
    GLint original_viewport[4];
    glGetIntegerv(GL_VIEWPORT, original_viewport);
```
at the very beginning of `_msdfgl_generate_glyphs_internal`, and then restore it at the very end with
```c
    glViewport(original_viewport[0], original_viewport[1],
               original_viewport[2], original_viewport[3]);
```

I would rather not add a callback to the end of glyph generation, as one can easily reach the same behavior by substituting it with their own callback function that calls `msdfgl_generate_glyph` at the beginning. I believe that with a similar setup you can also work around this issue:

```c
int missing_glyph_cb(msdfgl_font_t font, int32_t glyph, void *data) {
    /* Do the preparation, such as switch to a correct GL context. */

    int _ret = msdfgl_generate_glyph(font, glyph, NULL);  /* Generate the glyph */

    /* Do the cleanup, such as restore the context, viewport etc. */
    return _ret;
}


...
...
...
    msdfgl_set_missing_glyph_callback(msdfgl_ctx, missing_glyph_cb, NULL);
```

But I do agree, restoring the viewport should probably be done inside the library, as it is messing with it.

**Comment by xornet-sl** [comment]
I perfectly support that this should be done right in the library. Here is my MR: #7 
But after that I see that in demo application text is just fine, but MSDF picture isn't pretty now =)))
